### ISSUE TITLE
require explicit prefix for upload and bags scripts

### ISSUE THREAD

**Issue by jack-oquin** [utexas-bwi/bwi_lab#7]
I think we should consider always requiring the `-p` parameter. Otherwise people will often forget and end up using `bwi` by default. When running the scripts by hand, that's frequently not what is wanted.

If we do this, we could also make a similar change to the bwi_logging record node. I'm not sure that's really necessary, because the launch file always passes that parameter explicitly.

@pato: comments? suggestions?

**Comment by pato** [comment]
I definitely agree. I am all for removing any possible source of confusion. We should definitely enforce the parameter in the upload, and I believe we will also need to change the bwi_logging record node. AFAIK I only made the bwi parameter explicit in the launch file, but it still defaults to bwi in the node. I will assign this to myself and make those changes

**Comment by jack-oquin** [comment]
When typing the commands, it will be more convenient to replace the `-p` option with a mandatory positional argument:

```
 $ bwi bags [options] PREFIX
```

For consistency, that should work the same for both the `bags` and `upload` scripts.

**Comment by jack-oquin** [comment]
@pato: You did leave the `prefix` parameter default as `bwi` in the logging node. 

I'm content to leave that alone. Otherwise the logging node would have to refuse to run, not good behavior for a ROS node.

**Comment by jack-oquin** [comment]
@pato: I reassigned this issue to myself, because I'm ready to make this change, now.

Hope that does not interfere with anything you were already doing.

**Comment by jack-oquin** [comment]
It's working for me.
